name: ci-jvm

env:
  ADPARTNER_USERNAME: ${{ secrets.ADPARTNER_USERNAME }}
  ADPARTNER_PASSWORD: ${{ secrets.ADPARTNER_PASSWORD }}
  ADPARTNER_URL: ${{ secrets.ADPARTNER_URL }}

on:
  push:
    branches: [master]

permissions:
  packages: write

concurrency:
  group: ci-jvm

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: jdk11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: login gcr.io
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          logout: true
      - name: login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: cache ~/.m2
        uses: actions/cache@v3.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn clean compile
        run: $MVN clean compile
      - name: mvn test
        run: $MVN test
      - name: mvn package -DskipTests -Dquarkus.container-image.push=true latest
        if: github.ref == 'refs/heads/master'
        run: $MVN package -DskipTests -Dquarkus.container-image.push=true -Dquarkus.container-image.image=ghcr.io/ccjmne/fun7-services:latest '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
      - name: mvn package -DskipTests -Dquarkus.container-image.push=true snapshot
        if: github.ref != 'refs/heads/master'
        run: $MVN package -DskipTests -Dquarkus.container-image.push=true -Dquarkus.container-image.image=ghcr.io/ccjmne/fun7-services:snapshot '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
