name: ci-native

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/ci-native.yml"
      - "src/**"
      - "pom.xml"

permissions:
  packages: write

concurrency:
  group: ci-native

jobs:
  test-native:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: jdk11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: GraalVM 22.1.0
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 22.1.0
          native-image: true
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: cache ~/.m2
        uses: actions/cache@v3.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn clean verify -Pnative
        run: $MVN clean verify -Pnative

  # Split the jobs to avoid having the image push happen before native tests
  # (happens when running 'mvn clean verify -Pnative -Dquarkus.container-image.push=true')
  build-native:
    if: github.ref == 'refs/heads/master'
    needs: test-native
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      # - name: login gcr.io
      #   uses: docker/login-action@v2
      #   with:
      #     registry: gcr.io
      #     username: _json_key
      #     password: ${{ secrets.GCR_JSON_KEY }}
      #     logout: true
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: cache ~/.m2
        uses: actions/cache@v3.0.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn package -Pnative -DskipTests -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true
        run:
          $MVN package -Pnative -DskipTests -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.image=ghcr.io/ccjmne/fun7-services-native:latest '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
        # run:
        #   $MVN package -Pnative -DskipTests -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.image=gcr.io/fun7-357415/fun7-services-native:latest '-Dquarkus.jib.labels."org.opencontainers.image.revision"='$GITHUB_SHA
